### ISSUE TITLE
Log "github-request-id" response header when interacting with GitHub APIs

### ISSUE THREAD

**Issue by brphelps** [gradle/github-dependency-extractor#2]
This is a nice to have feature, but whenever something goes wrong it's much easier for folks on the GitHub side to diagnose when the GitHub Request ID headers are included (from the response payload). 

An example response header is: `x-github-request-id: 0400:95BA:46F3B20:48EAE9D:61E1C2BE`

We can use that header on our side to easily lookup a collection of different tracing info to help diagnose anything that may have gone awry, it's used throughout our APIs as a common identifier for the incoming call at the production GitHub level as well as throughout dependency graph's own APIs.

**Comment by JLLeitschuh** [comment]
Resolved! Much appreciated!

https://github.com/gradle/github-dependency-extractor/blob/2e571c0c2971c19872fc3694ab8af303b910eb01/plugin/src/main/kotlin/org/gradle/github/dependency/uploader/internal/DependencyUploaderService.kt#L64-L75
